name: Bump version and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Check commit message for 'release'
      run: |
        echo "Commit message: ${{ github.event.head_commit.message }}"
        if echo "${{ github.event.head_commit.message }}" | grep -qE '\brelease\b'; then
          echo "RELEASE_TRIGGER=true" >> $GITHUB_ENV
        else
          echo "RELEASE_TRIGGER=false" >> $GITHUB_ENV
          exit 78  # Optional: This exits the workflow early if 'release' is not in the commit message
        fi

    - name: Display current style.css before update
      if: env.RELEASE_TRIGGER == 'true'
      run: cat style.css

    - name: Bump version in style.css
      if: env.RELEASE_TRIGGER == 'true'
      id: bump_version
      run: |
        current_version=$(grep -oP 'Version:\s*\K[0-9.]+' style.css)
        echo "Current version: $current_version"
        
        IFS='.' read -r -a version_parts <<< "$current_version"
        version_parts[-1]=$((version_parts[-1] + 1))
        
        new_version="${version_parts[*]}"
        new_version="${new_version// /.}"
        
        awk -v new_version="$new_version" '{
          if ($1 == "Version:") {
            $2 = new_version
          }
          print
        }' style.css > style.css.tmp && mv style.css.tmp style.css
        
        updated_version=$(grep -oP 'Version:\s*\K[0-9.]+' style.css)
        echo "Updated version: $updated_version"
        
        if [ "$updated_version" != "$new_version" ]; then
          echo "Version update failed"
          exit 1
        fi
        
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Display current style.css after update
      if: env.RELEASE_TRIGGER == 'true'
      run: cat style.css

    - name: Commit changes
      if: env.RELEASE_TRIGGER == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add style.css
        git commit -m "Bump version to ${{ env.new_version }}"
        git push

    - name: Create new GitHub tag
      if: env.RELEASE_TRIGGER == 'true'
      run: |
        git tag -a "v${{ env.new_version }}" -m "Version ${{ env.new_version }}"
        git push origin "v${{ env.new_version }}"

    - name: Create zip file of the repository
      if: env.RELEASE_TRIGGER == 'true'
      run: |
        shopt -s extglob
        mkdir snn-brx-child-theme
        mv !(.git|*.github*|snn-brx-child-theme) snn-brx-child-theme/
        zip -r snn-brx-child-theme.zip snn-brx-child-theme -x "*.git*" "*.github*"
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

    - name: Create GitHub release
      if: env.RELEASE_TRIGGER == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: snn-brx-child-theme.zip
        tag_name: ${{ env.new_version }}
        release_name: Release ${{ env.new_version }}
        body: "Version ${{ env.new_version }} release of the project."

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
