# A descriptive name for the GitHub Actions workflow.  
name: Sync File to Another Repository

# This section defines the trigger for the workflow.
on:
  # The workflow will run on every push event.
  push:
    # It is restricted to only run on pushes to the 'main' branch.
    branches:
      - main

# This section defines the jobs that will run as part of the workflow.
jobs:
  # A single job named 'sync'.
  sync:
    # The job will run on the latest version of an Ubuntu virtual machine.
    runs-on: ubuntu-latest

    # This section lists the steps that the 'sync' job will execute.
    steps:
      # Step 1: Checks out your source repository's code.
      # This allows the workflow to access the file you want to sync.
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      # Step 2: Create a temporary directory to hold the file for syncing.
      # The push action works with directories, so we stage our single file here.
      - name: Stage file for syncing
        run: |
          mkdir -p temp_for_sync/includes
          cp includes/301-redirect.php temp_for_sync/includes/

      # Step 3: Uses a third-party action to push the staged file to the target repository.
      # The inputs have been corrected based on the action's requirements.
      - name: Push file to Target Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # IMPORTANT: The 403 Forbidden error means your secret token is missing permissions.
          # You must use a Personal Access Token (PAT) with the correct scope.
          #
          # HOW TO FIX:
          # 1. Go to your GitHub Settings > Developer settings > Personal access tokens > Tokens (classic).
          # 2. Generate a new token.
          # 3. Give it the 'repo' scope. This is required to push to other repositories.
          # 4. Copy the token and save it in this repository's Settings > Secrets and variables > Actions.
          # 5. Make sure the secret name is exactly 'SNNBRXSYNCSECRET'.
          API_TOKEN_GITHUB: ${{ secrets.SNNBRXSYNCSECRET }}
        with:
          # The directory containing the file(s) to sync.
          source-directory: 'temp_for_sync'
          
          # The GitHub username or organization that owns the destination repository.
          destination-github-username: 'sinanisler'
          
          # The name of the destination repository.
          destination-repository-name: 'snn-block'
          
          # The branch in the destination repository to push the file to.
          target-branch: 'main'

          # WARNING: This action will make the target directory an exact mirror of the source directory.
          # Any files in 'snn-block/includes' that are NOT in 'temp_for_sync/includes' WILL BE DELETED.
          # In this case, it will push '301-redirect.php' and delete all other files in that directory.
          target-directory: ''

          # The email for the user making the commit in the destination repository.
          user-email: 'actions@github.com'
          
          # The name of the user making the commit.
          user-name: 'GitHub Actions'
          
          # The commit message to be used for the sync.
          commit-message: 'ci: Automatic file sync from source repo'
