# A descriptive name for the GitHub Actions workflow.
name: Sync File to Another Repository

# This section defines the trigger for the workflow.
on:
  # The workflow will run on every push event.
  push:
    # It is restricted to only run on pushes to the 'main' branch.
    branches:
      - main

# This section defines the jobs that will run as part of the workflow.
jobs:
  # A single job named 'sync'.
  sync:
    # The job will run on the latest version of an Ubuntu virtual machine.
    runs-on: ubuntu-latest

    # This section lists the steps that the 'sync' job will execute.
    steps:
      # Step 1: Checks out your source repository's code.
      # This allows the workflow to access the file you want to sync.
      - name: Checkout Source Repo
        uses: actions/checkout@v4

      # Step 2: Create a temporary directory to hold the file for syncing.
      # The push action works with directories, so we stage our single file here.
      - name: Stage file for syncing
        run: |
          mkdir temp_for_sync
          cp includes/301-redirect.php temp_for_sync/

      # Step 3: Uses a third-party action to push the staged file to the target repository.
      # The inputs have been corrected based on the action's requirements.
      - name: Push file to Target Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # A secret token is required to grant permission to push to the other repository.
          # This should be stored in your repository's secrets.
          API_TOKEN_GITHUB: ${{ secrets.SNNBRXSYNCSECRET }}
        with:
          # The directory containing the file(s) to sync.
          source-directory: 'temp_for_sync'
          
          # The GitHub username or organization that owns the destination repository.
          destination-github-username: 'sinanisler'
          
          # The name of the destination repository.
          destination-repository-name: 'snn-block'
          
          # The branch in the destination repository to push the file to.
          target-branch: 'main'

          # The directory within the destination repo where the files will be placed.
          target-directory: 'includes'

          # The email for the user making the commit in the destination repository.
          user-email: 'actions@github.com'
          
          # The name of the user making the commit.
          user-name: 'GitHub Actions'
          
          # The commit message to be used for the sync.
          commit-message: 'ci: Automatic file sync from source repo'
